config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'static_pages#home', as: 'home'

  get '/contact', to: 'static_pages#contact', as: 'contact'

  get '/about', to: 'static_pages#about', as: 'about'
  get '/about/me', to: 'static_pages#about_me', as: 'about_me'
  get '/about/group', to: 'static_pages#about_group', as: 'about_group'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end

  def about_me
  end

  def about_group
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JeMePresente</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"/>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #c70039">
    <a class="navbar-brand" href="#">Madagascar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="<%= home_path%>">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            About
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="<%= about_me_path%>">About me</a>
            <a class="dropdown-item" href="<%= about_group_path%>">About group</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= contact_path%>">Contact</a>
        </li>
      </ul>
    </div>
  </nav>
    <%= yield %>
  </body>
  <script
  src="http://code.jquery.com/jquery-3.3.1.slim.min.js"
  integrity="sha256-3edrmyuQ0w65f8gfBsqowzjJe2iM6n0nKciPUp8y+7E="
  crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
</html>

app/views/static_pages/about.html.erb
<div class="alert alert-primary alert-dismissible fade show" role="alert">
  Bienvenue sur la page <strong>About</strong>.
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/static_pages/about_group.html.erb
<%= link_to 'Couou', the_joker_path('itokiana')%>

<div class="alert alert-success alert-dismissible fade show" role="alert">
  Bienvenue sur la page <strong>About group</strong>.
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/static_pages/about_me.html.erb
<div class="alert alert-success alert-dismissible fade show" role="alert">
  Bienvenue sur la page <strong>About me</strong>.
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/static_pages/contact.html.erb
<div class="alert alert-success alert-dismissible fade show" role="alert">
  Bienvenue sur la page <strong>Contact</strong>.
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/static_pages/home.html.erb
<div class="alert alert-success alert-dismissible fade show" role="alert">
  Bienvenue sur la page <strong>Home</strong>.
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>